### ISSUE TITLE
Great things were planned

### ISSUE THREAD

**Issue by ghost** [Catacomb-Snatch/Catacomb-Snatch#6]
But nothings happening here..
Sad ._.

**Comment by andy36** [comment]
I know this was long ago but I'd be interested in the list of planned features and getting this going again. I see that come commits have been coming in.

**Comment by Maescool** [comment]
@andy36 Like a lot of projects, if someone isn't pushing it, nothing happens, and for most of us who worked on this, time has become such a finite thing, with all the side projects and some things we have to do in life like day jobs etc, it's hard to find the time to spent on this project.
All of you are however free to commit stuff ;)

**Comment by godleydemon** [comment]
@andy36 what the ideas were here, is reprogramming it from scratch to utilize libgdx I believe to be compatible with things like the Ouya, android, ios and windows. Creating the ability to open the market up a little more to more devices. Better gamepad support and completely redone multiplayer utilizing libgdx. We also planned at some point in time, creating a center server you could create games on, usernames, win loss ratios and the ability to purchase hats for tokens. Don't know if hats every got off the ground since it'd require some serious modification to the original sprites. But yeah, we had alot planned, it just never really happened and we all got to busy with everything in real life. 

I think everyone comes back to this every once in a while in hoping the core part of the libgdx port is done. But I think right now, all it does is launch the game/menu and that's about it. It does work on the Ouya though! XD

Feel free to contribute to the code base if you like, Maescool still pays attention to it and so does space when he has time. Kyle I believe stops by from time to time as well to check things out and do commits when necessary.
